# Generated by Django 5.2.17 on 2026-09-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=50)),
                ('prompt_ref', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_creation_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'model'], name='core_llmcal_provide_6198e8_idx'), models.Index(fields=['created_at'], name='core_llmcal_created_1754e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cache_write_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cache_read_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='core.llmcall')),
            ],
        ),
    ]
