# Generated by Django 5.2.17 on 2026-09-16 08:40

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ordinal', models.PositiveIntegerField()),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'ordinal'],
                'constraints': [models.UniqueConstraint(fields=('document', 'ordinal'), name='uniq_chunk_doc_ordinal')],
            },
        ),
    ]
