# Generated by Django 5.2.17 on 2026-09-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
